ALTER TABLE public.settings
  ADD COLUMN IF NOT EXISTS row_color TEXT DEFAULT '#000000',
  ADD COLUMN IF NOT EXISTS row_opacity NUMERIC DEFAULT 0.5,
  ADD COLUMN IF NOT EXISTS row_radius TEXT DEFAULT '8px',
  ADD COLUMN IF NOT EXISTS row_gap INTEGER DEFAULT 8,
  ADD COLUMN IF NOT EXISTS top3_highlight_enabled BOOLEAN DEFAULT true,
  ADD COLUMN IF NOT EXISTS top1_color TEXT DEFAULT '#ffd700',
  ADD COLUMN IF NOT EXISTS top2_color TEXT DEFAULT '#c0c0c0',
  ADD COLUMN IF NOT EXISTS top3_color TEXT DEFAULT '#cd7f32',
  ADD COLUMN IF NOT EXISTS highlight_new BOOLEAN DEFAULT true;
